### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by zachHixson** [halojedi20/jsMatrix#3]
Without a license it's legal gray area whether or not someone can use/modify this code. Would you mind choosing a license and adding it to the repo?

An MIT is kind of a "whatever man, have fun," type license which is probably what you're after considering you released it without one, though if that's not what you intended I'd recommend researching one that suits what you want better.

**Comment by halfmatthalfcat** [comment]
Added an MIT license. I completely forgot about this lib ha.
